name: E2E - Octomind P2P 

on:
  pull_request:    
  push:

jobs:
  run-e2e-p2p-tests-default:

    if: >
      github.event_name == 'pull_request' ||
      github.event_name == 'push'

    runs-on: ubuntu-latest
    name: E2E Octomind P2P - default

    steps:
      - name: Execute Octomind Tests
        uses: OctoMind-dev/automagically-action-execute@v2
        with:
          url: 'https://staging-home.deriv.com/dashboard'
          token: ${{ secrets.OCTOMIND_API_KEY }}
          testTargetId: 'e5e266e1-4eca-4639-b649-6d2d289cdeca'
          blocking: false